### ISSUE TITLE
breaks redir conditions

### ISSUE THREAD

**Issue by SimJoSt** [nicolasazrak/caddy-cache#22]
Using the `cache` directive in the same host as the `redir` directive breaks the functionality of conditions in the latter. The conditions are not properly evaluated and depending if a statement or a negated statement is used, all or none of the requests are redirected, regardless if the condition matches or not.

In this first example, it will redirect no requests:
```
example.com {
	cache
	redir {
		if {uri} is /1
		/2
	}
}
```

In this second example, it will redirect all requests:
```
example.com {
	cache
	redir {
		if {uri} not /1
		/2
	}
}
```

Removing the `cache` directive from these examples restores the desired behavior.

**Comment by nicolasazrak** [comment]
After looking a little bit the code of caddy I found out that it saves a lot of information in the request context. The problem is that the cache when doing a request to the upstream creates a new context to prevent being canceled if the original request is canceled (https://github.com/nicolasazrak/caddy-cache/blob/master/handler.go#L128), the problem with that is that the replacer does not have the information to change `{uri}` to the current value.

I will try to implement a fix for this as soon as possible.

**Comment by nicolasazrak** [comment]
I pushed a new commit on master that fixs this issue. I tried to deploy the new version but there is a problem with the caddy infrastructure (https://github.com/mholt/caddy/issues/2106). I will release the update when the new caddy version is released.

**Comment by nicolasazrak** [comment]
Today I deployed the fix to the caddy page. Could you download it and tell me if now it's working?

**Comment by SimJoSt** [comment]
I tested it on a local environment. Seems to be resolved. I didn't experience any issues using the cache directive.
Thank you and good work!
