### ISSUE TITLE
LGPL Licence

### ISSUE THREAD

**Issue by CMogilko** [nicolasazrak/caddy-cache#41]
Hi,
Don't you think that `caddy-cache`'s licence should be changed to anything more friendly?
Apache2 maybe, because `mholt/caddy` has Apache2.
`caddy-cache` is a great project, but I (and maybe many others) can't use it because of the licence. Most of the golang's projects and `caddy` itself use non-*GPL and it's okay. Although LGPL is a less strict, in case of golang it has no sense because there is no dynamic linking.

**Comment by mholt** [comment]
The first requirement for publishing a plugin is indeed to use a license that is compatible with Caddy's license: https://github.com/mholt/caddy/wiki/Publishing-a-Plugin-to-the-Download-Page#before-you-publish

Unfortunately, LGPL isn't compatible, so @nicolasazrak if you can change it to something else, we can keep it on the site, otherwise I'll have to un-publish it. :(

**Comment by nicolasazrak** [comment]
@mholt Fair enough, I'm changing the license to MPL 2.0. I want every user to be able to use my code, even in closed source software but any change must be published. From what I understand MPL is similar to LGPL but allows static linking. Is it compatible with caddy license?

**Comment by mholt** [comment]
The [wikipedia article for MPL](https://en.wikipedia.org/wiki/Mozilla_Public_License) says:

> Therefore, in early 2010, after more than a decade without modification, an open process for creating version 2.0 of the MPL began. Over the next 21 months, the MPL was not only changed to make the license clearer and easier to apply, but also to achieve compatibility with the GPL and Apache licenses.

I am not a lawyer, but based on that (and some light reading on Mozilla's website), I think it is compatible.

Thanks!

**Comment by nicolasazrak** [comment]
Done, now `caddy-cache` is licensed with MPL 2.0

**Comment by CMogilko** [comment]
@mholt https://www.mozilla.org/en-US/MPL/2.0/FAQ/ says that if nobody modifies MPL2 code - it's okay. But if you do, you have to publish sources. Unlike Apache2.
So if any of users of Caddy make private changes to Caddy - it's okay. But if someone does any private changes to `caddy-cache` -- it is violation.
If you think it is compatible - I'm ok with that. But I think someone can miss out this point.

@nicolasazrak Thank you for response.

**Comment by mholt** [comment]
Yeah, it's fine I think since we don't modify the plugin, and we only need to distribute it in a way that is compatible with our license, so, it should be fine. The burden of respecting licenses is of course on anyone else who builds from source, especially if they make changes or redistribute, so that is their responsibility.

Thank you!
