### ISSUE TITLE
Submit this to caddyserver.com

### ISSUE THREAD

**Issue by hacdias** [nicolasazrak/caddy-cache#9]
Hello!

Are there any plans to submit this plugin to the Caddy website? It would be pretty useful!

Thanks 😄

**Comment by nicolasazrak** [comment]
I would love to publish this but it still is an experiment and it needs to be polished. Caching is a difficult task and I don't want to submit something that is not ready. I work on this from time to time and if anytime I make it better I'll send the PR to publish it.

**Comment by hacdias** [comment]
Thanks! I'll be looking forward to see this evolve 😄

**Comment by martindale** [comment]
Can we get some better instructions on how to compile and run this in production, then?  This is the one non-standard plugin that I'd like to use, but it's never been clear how to run a compiled-from-source version of Caddy in production.

**Comment by nicolasazrak** [comment]
@martindale I just updated the readme with setup instructions, I hope it helps, tell me if something does not work

**Comment by mholt** [comment]
@nicolasazrak What can we do to help you get this on the Caddy website? It's okay if it's still somewhat experimental, just mention that in its description.

**Comment by nicolasazrak** [comment]
@mholt I have just added about the experimental status in the description. 

The problem with this plugin and the reason that I haven't asked to be published in caddy website it that It doesn't handle concurrency well. 

For example: if two requests come at the same time, both should check the internal cache, if the resource is not there, only one should fetch the upstream server and if the headers say the content is cacheable, serve the headers and content to both at the same time while is being downloaded from the first request. And if a third request hits the server, first it needs send the already downloaded content, then "subscribe" to the download stream (made by the first request) and serve from there.

The problem is that when I started creating this plugin I only considered the simple case where there is only one concurrent request, without thinking about the above case. In case two requests hit the server, one will have to wait until the first ends. So when trying to fix this I noted that the current design didn't work for that and it should be changed. 

A few days ago I was thinking about a new design and it should be something like this: https://gist.github.com/nicolasazrak/b1130c3647c42be5bd4de5831f61cf67

**Comment by mholt** [comment]
@nicolasazrak Ah, I see why you're waiting. I agree that concurrent requests should not be an afterthought. ;) Can't wait to see it ready to publish!

**Comment by nicolasazrak** [comment]
Closed because now it is published https://caddyserver.com/docs/http.cache

**Comment by hacdias** [comment]
Cool! 😄 Congrats @nicolasazrak
